### ISSUE TITLE
Make patching easier

### ISSUE THREAD

**Issue by amunn** [OpenLogicProject/fitch#7]
Hi, is there any reason why `*` has been used as the internal command character as opposed to `@`? It would user patching of the package much easier, since `\makeatletter`...`\makeatother` could be used. (Context: this [TeX.se answer](https://tex.stackexchange.com/q/698605)).  A quick test shows that a global replacement of `*` with `@` in the package and removal of the catcode modifications should bring the package into line with most other packages.

**Comment by rzach** [comment]
This is already done and will be in v1.0 https://github.com/OpenLogicProject/fitch/releases/tag/v1.0-beta

**Comment by amunn** [comment]
Great. Even without your new additions, this is a good change to make.
